[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "dungeon_generator"
version = "0.1.0"
description = "A dungeon generator using graph theory and Pygame for visualization."
readme = "README.md"
requires-python = ">=3.10, <3.16"
authors = [{"name" = "Tryno"}]

classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
]

dependencies = [
    "pygame==2.6.1",
]